# Generated by Django 5.1.7 on 2025-05-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Narratica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='cover_art_thumbnail',
        ),
    ]
