# Generated by Django 5.1.6 on 2025-03-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narratica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookchapter',
            name='chapter_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
